export const POST_ORDER_REQUEST: 'POST_ORDER_REQUEST' = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS' = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILED: 'POST_ORDER_FAILED' = 'POST_ORDER_FAILED';
export const CLOSE_ORDER_MODAL: 'CLOSE_ORDER_MODAL' = 'CLOSE_ORDER_MODAL';
export const OPEN_ORDER_MODAL: 'OPEN_ORDER_MODAL' = 'OPEN_ORDER_MODAL';
export const CLEAR_ORDER_ERROR: 'CLEAR_ORDER_ERROR' = 'CLEAR_ORDER_ERROR';
export const CLOSE_ORDER_DETAIL_MODAL: 'CLOSE_ORDER_DETAIL_MODAL' = 'CLOSE_ORDER_DETAIL_MODAL';
export const OPEN_ORDER_DETAIL_MODAL: 'OPEN_ORDER_DETAIL_MODAL' = 'OPEN_ORDER_DETAIL_MODAL';
